
spring:
  data:
    mongodb:
      username: jlijindabaad
      password: jlijindabaad
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
server:
  port: 8088